\ $Id: CommandID.f,v 1.26 2012/05/08 20:57:38 georgeahubert Exp $
\    File: CommandID.f
\
\  Author: Dirk Busch (dbu)
\   Email: dirkNOSPAM@win32forth.org
\
\ Created: Mittwoch, Juni 09 2004 - dbu
\ Updated: Samstag, Juli 03 2004 - 10:52 - dbu

\ Saturday, May 06 2006  Added Print and PageSetup - Rod

cr .( Loading Menu Command ID's...)

: NewID ( <name> -- )
        defined
        IF  drop
        ELSE NextID swap count ['] constant execute-parsing
        THEN ;

IdCounter constant IDM_FIRST

\ File menu
NewID IDM_NEW_SOURCE_FILE
NewID IDM_OPEN_SOURCE_FILE
NewID IDM_CLOSE
NewID IDM_SAVE
NewID IDM_SAVE_AS
NewID IDM_SAVE_ALL
NewID IDM_RELOAD
NewID IDM_OPEN_HTML_FILE
NewID IDM_PRINT
NewID IDM_PAGE_SETUP
NewID IDM_EXIT
NewID IDM_OPEN_RECENT_FILE
NewID IDM_OPEN_HIGHLIGHTED_FILE
NewID IDM_NEW_HTML_SOURCE_FILE

\ Edit menu
NewID IDM_UNDO
NewID IDM_REDO
NewID IDM_CUT
NewID IDM_COPY
NewID IDM_PASTE
NewID IDM_DELETE
NewID IDM_SELECT_ALL
NewID IDM_REMOVE_SELECTION
NewID IDM_FIND_TEXT
NewID IDM_FIND_NEXT
NewID IDM_FIND_PREVIOUS
NewID IDM_FIND_IN_FILES
NewID IDM_INSERT_DATE
NewID IDM_INSERT_DATE&TIME
NewID IDM_COMMENT_BLOCK
NewID IDM_UNCOMMENT_BLOCK
NewID IDM_LOWERCASE
NewID IDM_UPPERCASE
NewID IDM_LINECUT
NewID IDM_LINEDELETE
NewID IDM_LINECOPY
NewID IDM_LINETRANSPOSE
NewID IDM_LINEDUPLICATE
NewID IDM_REPLACE_TEXT
NewId IDM_NORMALSELECTION
NewId IDM_COLUMNSELECTION
NewId IDM_LINESELECTION

\ DexH menu
NewID IDM_DEX_GLOSSARY
NewID IDM_DEX_PARAGRAPH
NewID IDM_DEX_CODE_PARAGRAPH
NewID IDM_DEX_STYLE_BOLD
NewID IDM_DEX_STYLE_ITALIC
NewID IDM_DEX_STYLE_TYPEWRITER

\ View menu
NewID IDM_VIEW_EOL
NewID IDM_VIEW_WHITESPACE
NewID IDM_VIEW_LINE_NUMBERS
NewID IDM_COLORIZE
NewID IDM_BROWSE
NewID IDM_HTML_PREVIEW

\ Options menu
NewID IDM_EOL_CRLF
NewID IDM_EOL_LF
NewID IDM_EOL_CR
NewID IDM_CREATE_BAK
NewID IDM_SAVE_ALL_BEFORE_COMPILE
NewID IDM_TABS
NewID IDM_SHOW_TOOLBAR
NewID IDM_SHOW_STATUSBAR
NewID IDM_REMOVE_TRAILING_WHITE
NewID IDM_ENSURE_FINAL_LINE_ENDING
NewID IDM_COMPILE_PROJECT
NewID IDM_PREFERENCES
NewID IDM_SAVEDEFAULT_SESSION
NewID IDM_LOADDEFAULT_SESSION
NewID IDM_SAVEDEFAULTS

\ Win32Forth menu
NewID IDM_COMPILE
NewID IDM_COMPILE_SELECTION
NewID IDM_COMPILE_LINE
NewID IDM_DEBUG
NewID IDM_SET_BREAK_POINT
NewID IDM_BOOKMARKs
NewID IDM_SET_BOOKMARK
NewID IDM_BUILD_CODE_TREE
NewID IDM_MSGBOX_BUILDER

\ Window menu
NewID IDM_TILE_HORIZONTAL
NewID IDM_TILE_VERTICAL
NewID IDM_ARRANGE
NewID IDM_CASCADE
NewID IDM_CLOSE_ALL

NewID IDM_SPLIT_HORIZONTAL
NewID IDM_SPLIT_VERTICAL
NewId IDM_NO_SPLIT_WINDOW

\ Help menu
NewID IDM_W32F_DOC
NewID IDM_WORDHELP
NewID IDM_ABOUT

\ Toolbar
NewID IDM_BACK
NewID IDM_FORWARD

\ Project Manager
\ NewID IDM_SHOW_FILE
NewID IDM_EXECUTEFILE_PRJ
NewID IDM_NEW_PRJ
NewID IDM_OPEN_PRJ
NewID IDM_SAVE_PRJ
NewID IDM_SAVE_AS_PRJ
NewID IDM_RENAME_PRJ
NewID IDM_BUILD_PRJ
NewID IDM_REBUILD_PRJ
NewID IDM_SET_BUILD_PATH_PRJ
NewID IDM_COMPILE_PRJ
NewID IDM_SET_FORTH_PRJ
NewID IDM_NEW_MODULE_PRJ
NewID IDM_ADD_PRJ
NewID IDM_DELETE_PRJ
NewID IDM_ADD_FORMS_PRJ
NewID IDM_ZIP_PRJ
\ NewID IDM_ADD_PRJ
NewID IDM_COPY_PRJ
NewID IDM_OPEN_RECENT_FILE_PRJ
NewID IDM_SHOWPROJECT_TAB
NewID IDM_CLOSE_PRJ
NewID IDM_ADD_OPEN_PRJ

\ Form Designer
NewID IDM_FORM_New
NewID IDM_FORM_Open
NewID IDM_FORM_Save
NewID IDM_FORM_SaveAs
NewID IDM_FORM_Delete
NewID IDM_FORM_Copy
NewID IDM_FORM_Write
NewID IDM_FORM_Test
NewID IDM_FORM_ControlProperty
NewID IDM_FORM_FormProperty
NewID IDM_FORM_Editor
NewID IDM_FORM_TabOrder
NewID IDM_FORM_SaveSession  \ save the current state of the system to a file
NewID IDM_FORM_Loadsession  \ reload a saved state
NewID IDM_FORM_CloseAll
NewID IDM_FORM_Close
NewID IDM_FORM_SaveAll
NewID IDM_FORM_MoveToBack
NewID IDM_FORM_MoveToFront
NewID IDM_FORM_merge
NewID IDM_FORM_GroupAction
NewID IDM_FORM_CreateToolBar
NewID IDM_FORM_Splitter
NewID IDM_FORM_CreateMenu
NewID IDM_FORM_(OPEN)
NewID IDM_FORM_PropertyForm
NewID IDM_FORM_WriteAll
NewId IDM_FORM_SELECT
NewId IDM_FORM_BITMAP
NewId IDM_FORM_LABEL
NewId IDM_FORM_TEXTBOX
NewId IDM_FORM_GROUPBOX
NewId IDM_FORM_PUSHBUTTON
NewId IDM_FORM_CHECKBOX
NewId IDM_FORM_RADIOBUTTON
NewId IDM_FORM_COMBOBOX
NewId IDM_FORM_LISTBOX
NewId IDM_FORM_HORIZSCROLL
NewId IDM_FORM_VERTSCROLL
NewId IDM_FORM_GENERIC
NewId IDM_FORM_FILEWINDOW
NewId IDM_FORM_TABCONTROL
NewID IDM_SHOW_FORMTAB
NewID IDM_FORM_AddToProject
NewID IDM_FORM_ADDCODE
NewID IDM_TURNKEY_FORM
NewID IDM_ZOOMIN
NewID IDM_ZOOMOUT

IdCounter constant IDM_LAST

: allot-erase	( n -- )
		here over allot swap erase ;

Create CommandTable IDM_LAST IDM_FIRST - cells allot-erase

: IsCommand?	( ID -- f )
		IDM_FIRST IDM_LAST within ;

: >CommandTable	( ID -- addr )
		dup IsCommand?
		if   IDM_FIRST - cells CommandTable +
		else drop abort" error - command ID out of range"
		then ;

: DoCommand	( ID -- )
		>CommandTable @ ?dup IF execute THEN ;

: SetCommand	( ID -- )
		last @ name> swap >CommandTable ! ;
