\    File: ScintillaLexer.f
\
\  Author: Dirk Busch (dbu)
\   Email: dirkNOSPAM@win32forth.org
\
\ Created: Donnerstag, Juni 10 2004 - 13:11 - dbu
\ Updated: Sonntag, Juli 11 2004 - 11:53 - dbu
\
\ Win32Forth-Lexer support for "Scintilla source code edit control".
\ See www.scintilla.org for more information about the control.

\ Note: - coloring of multi line comment's need some more work to do

cr .( Loading Scintilla Lexer...)


\ -----------------------------------------------------------------------------
\ Create the list's with the keywords.
\ Note the keywords in the list's must be im UPPERCASE !!!
\ -----------------------------------------------------------------------------

: (,$)     ( a len -- )  BOUNDS ?DO I C@ C, LOOP ;
: ,{       ( <text> -- ) [CHAR] } WORD COUNT -TRAILING (,$) BL C, ;

create ANSKeywords \ ANS words
,{ ! # #> #S * */ */MOD + +! , - . / /MOD 0< 0= 1+ 1- 2! 2* 2/ 2@ 2DROP }
,{ 2DUP 2OVER 2SWAP < <# = > >BODY >IN >NUMBER >R ?DUP @ ABS ACCEPT ALIGN ALIGNED }
,{ ALLOT AND BASE BL C! C, C@ CELL+ CELLS CHAR CHAR+ CHARS COUNT CR DECIMAL DEPTH }
,{ DROP DUP EMIT EVALUATE EXECUTE FILL FIND FM/MOD HERE HOLD I INVERT J KEY LITERAL }
,{ LSHIFT M* MAX MIN MOD MOVE NEGATE OR OVER R> R@ ROT RSHIFT S>D }
,{ SIGN SM/REM SOURCE SPACE SPACES STATE SWAP TYPE U. U< UM* UM/MOD WORD XOR }
,{ #TIB .R 0<> 0> 2>R 2R> 2R@ <> COMPILE, CONVERT ERASE EXPECT FALSE HEX NIP PAD }
,{ PARSE PICK QUERY REFILL RESTORE-INPUT ROLL SAVE-INPUT SOURCE-ID SPAN TIB }
,{ TRUE TUCK U.R U> UNUSED WITHIN BLK BLOCK BUFFER FLUSH LOAD }
,{ SAVE-BUFFERS UPDATE EMPTY-BUFFERS LIST REFILL SCR THRU 2LITERAL D+ D- D. D.R }
,{ D0< D0= D2* D2/ D< D= D>S DABS DMAX DMIN DNEGATE M*/ M+ 2ROT DU< AT-XY KEY? }
,{ PAGE EKEY EKEY>CHAR EKEY? EMIT? MS TIME&DATE BIN CLOSE-FILE CREATE-FILE }
,{ DELETE-FILE FILE-POSITION FILE-SIZE OPEN-FILE R/O R/W }
,{ READ-FILE READ-LINE REPOSITION-FILE RESIZE-FILE SOURCE-ID W/O WRITE-FILE }
,{ WRITE-LINE FILE-STATUS FLUSH-FILE REFILL RENAME-FILE >FLOAT D>F F! F* F+ F- }
,{ F/ F0< F0= F< F>D F@ FALIGN FALIGNED FDEPTH FDROP FDUP FLITERAL FLOAT+ FLOATS }
,{ FLOOR FMAX FMIN FNEGATE FOVER FROT FROUND FSWAP REPRESENT DF! DF@ DFALIGN }
,{ DFALIGNED DFLOAT+ DFLOATS F** F. FABS FACOS FACOSH FALOG FASIN FASINH FATAN }
,{ FATAN2 FATANH FCOS FCOSH FE. FEXP FEXPM1 FLN FLNP1 FLOG FS. FSIN FSINCOS FSINH }
,{ FSQRT FTAN FTANH F~ PRECISION SET-PRECISION SF! SF@ SFALIGN SFALIGNED SFLOAT+ }
,{ SFLOATS ALLOCATE FREE RESIZE .S ? DUMP SEE WORDS AHEAD }
,{ ASSEMBLER BYE CS-PICK CS-ROLL EDITOR FORGET STATE FIND FORTH-WORDLIST }
,{ GET-CURRENT GET-ORDER SEARCH-WORDLIST SET-CURRENT SET-ORDER WORDLIST FORTH ORDER }
,{ -TRAILING /STRING BLANK CMOVE CMOVE> COMPARE SEARCH SLITERAL }

create commentStart \ multi line comments start
,{ COMMENT: /* (( (* DOC }

create commentEnd \ multi line comments end
,{ COMMENT; */ )) *) ENDDOC }

create UserWords1
,{ : ; :CLASS ;CLASS :OBJECT ;OBJECT :M ;M CREATE DOES> CODE ;CODE }
,{ VARIABLE CONSTANT FVARIABLE FCONSTANT 2VARIABLE 2CONSTANT VALUE }
,{ 2VALUE FVALUE BUFFER: }
,{ <SUPER :NONAME C; ;C DEFER IS ACTION-OF HEADER ALIAS SYNONYM USER NEWUSER }
,{ EQU CFA-CODE NCODE |: END-CODE TO +TO <OBJECT <CLASS SUPER SELF }
,{ IF -IF ELSE THEN ENDIF DO ?DO LOOP +LOOP UNLOOP EXIT LEAVE }
,{ RECURSE BEGIN UNTIL WHILE REPEAT AGAIN CASE ENDCASE ENDOF OF }
,{ CATCH THROW ABORT QUIT AS MACRO #DEFINE }
,{ RECORD: ;RECORD ;RECORDSIZE: BYTES BYTE BITS SHORT INT DINT }
,{ MACRO: ENDM SUBR: CFA-FUNC |CLASS USEROBJECT: }
,{ DEFAULTOF RANGEOF "OF "OF-BEGIN "OF-CONTAIN |OF |IF }

create UserWords2
,{ VOCABULARY DEFINITIONS ALSO ONLY PREVIOUS }
,{ IN-APPLICATION IN-SYSTEM IN-CODE IN-PREVIOUS \IN-SYSTEM-OK \- \+ }
,{ SYS-WARNING-OFF SYS-WARNING-ON }
,{ MARKER ANEW INTERNAL PRIVATE EXTERNAL MODULE }
,{ ' ['] [CHAR] [COMPILE] POSTPONE IMMEDIATE }
,{ #LEXICON LEXICON #VOCABULARY }
,{ ENVIRONMENT? }

create UserWords3
,{ [DEFINED] [UNDEFINED] [IF] [ELSE] [THEN] [ENDIF] }
,{ #IFDEF #IFNDEF #IF #ELSE #THEN #ENDIF }
,{ [ ] }
,{ INCLUDE-FILE INCLUDED $FLOAD FLOAD SYS-FLOAD "FLOAD INCLUDE NEEDS }
,{ REQUIRED REQUIRE }
,{ ("LOADED?) "LOADED? LOADED? \LOADED- \LOADED }
,{ SAVE TURNKEY FSAVE APPLICATION }
,{ OK }

create UserWords4
,{ WINLIBRARY PROC CALL EXTERN }

create UserWords5
,{ (LOCAL) LOCALS| | }

create UserWords6
,{  }

#define SCE_FORTH_DEFAULT 0
#define SCE_FORTH_COMMENT 1
#define SCE_FORTH_STRING  2
#define SCE_FORTH_NUMBER  3
#define SCE_FORTH_LOCALS  4
#define SCE_FORTH_ANS     5
#define SCE_FORTH_USER1   6
#define SCE_FORTH_USER2   7
#define SCE_FORTH_USER3   8
#define SCE_FORTH_USER4   9
#define SCE_FORTH_USER5   10
#define SCE_FORTH_USER6   11

  0   0   0  palettergb constant COL_FORTH_DEFAULT
  0 128   0  palettergb constant COL_FORTH_COMMENT
  0   0 128  palettergb constant COL_FORTH_ANS
128  64   0  palettergb constant COL_FORTH_STRING
128  64   0  palettergb constant COL_FORTH_NUMBER
128  64   0  palettergb constant COL_FORTH_LOCALS
  0   0 255  palettergb constant COL_FORTH_USER1
  0 128 128  palettergb constant COL_FORTH_USER2
255   0   0  palettergb constant COL_FORTH_USER3
128 128   0  palettergb constant COL_FORTH_USER4
128  64   0  palettergb constant COL_FORTH_USER5
 64  64   0  palettergb constant COL_FORTH_USER6



