Anew -DpAnsfCheck.f

\ To check if a source only uses DPANS'94 definitions.
\ Just load this file and then load the source to check.
\ When it is not DPANS then it will display:
\ Error(-13): FOO is undefined in file ......
\ See http://win32forth.sourceforge.net/doc/dpans/dpans1.htm#1.
\ for the DEPRECATED definitions
\ The block extension words are excluded.

DPR-WARNING-OFF

vocabulary dpans also dpans  definitions
\in-system-ok  : dpansOnly ( - ) dpans only dpans definitions ;

synonym -       -             (   .6.1.0160     minus    CORE  )
synonym -TRAILING  -TRAILING  ( 17.6.1.0170     dash-trailing    STRING )
synonym ,       ,             (   .6.1.0150     comma    CORE  )
synonym ;       ;             (   .6.1.0460     semicolon        CORE  )
synonym ;CODE   ;CODE         ( 15.6.2.0470     semicolon-code   TOOLS EXT )
synonym :       :             (   .6.1.0450     colon    CORE  )
synonym :NONAME :NONAME       (   .6.2.0455     colon-no-name    CORE EXT  )
synonym !       !             (   .6.1.0010     store    CORE  )
synonym ?       ?             ( 15.6.1.0600     question         TOOLS  )
synonym ?DO     ?DO           (   .6.2.0620     question-do      CORE EXT  )
synonym ?DUP    ?DUP          (   .6.1.0630     question-dupe    CORE  )
synonym .       .             (   .6.1.0180     dot      CORE  )
synonym ."      ."            (   .6.1.0190     dot-quote        CORE  )
synonym .(      .(            (   .6.2.0200     dot-paren        CORE EXT  )
synonym .R      .R            (   .6.2.0210     dot-r    CORE EXT  )
synonym .S      .S            ( 15.6.1.0220     dot-s    TOOLS  )
synonym '       '             (   .6.1.0070     tick     CORE  )
synonym (       (             (   .6.1.0080     paren    CORE  )
\ synonym (     (             ( 11.6.1.0080     paren    FILE  )
synonym (LOCAL) (LOCAL)       ( 13.6.1.0086     paren-local-paren        LOCAL  )
synonym [       [             (   .6.1.2500     left-bracket     CORE  )
synonym [']     [']           (   .6.1.2510     bracket-tick     CORE  )
synonym [CHAR]  [CHAR]        (   .6.1.2520     bracket-char     CORE  )
synonym [COMPILE] [COMPILE]   (   .6.2.2530     bracket-compile  CORE EXT  )
synonym [ELSE]  [ELSE]        ( 15.6.2.2531     bracket-else     TOOLS EXT )
synonym [IF]    [IF]          ( 15.6.2.2532     bracket-if       TOOLS EXT )
synonym [THEN]  [THEN]        ( 15.6.2.2533     bracket-then     TOOLS EXT )
synonym ]       ]             (   .6.1.2540     right-bracket    CORE  )
synonym @       @             (   .6.1.0650     fetch    CORE  )
synonym *       *             (   .6.1.0090     star     CORE  )
synonym */      */            (   .6.1.0100     star-slash       CORE  )
synonym */MOD   */MOD         (   .6.1.0110     star-slash-mod   CORE  )
synonym /       /             (   .6.1.0230     slash    CORE  )
synonym /MOD    /MOD          (   .6.1.0240     slash-mod        CORE  )
synonym /STRING /STRING       ( 17.6.1.0245     slash-string     STRING )
synonym \       \             (   .6.2.2535     backslash        CORE EXT  )
\ synonym \     \             (  7.6.2.2535     backslash        BLOCK EXT )
synonym #       #             (   .6.1.0030     number-sign      CORE  )
synonym #>      #>            (   .6.1.0040     number-sign-greater      CORE  )
synonym #S      #S            (   .6.1.0050     number-sign-s    CORE  )
synonym #TIB    #TIB          (   .6.2.0060     number-t-i-b     CORE EXT  ) DEPRECATED
synonym +       +             (   .6.1.0120     plus     CORE  )
synonym +!      +!            (   .6.1.0130     plus-store       CORE  )
synonym +LOOP   +LOOP         (   .6.1.0140     plus-loop        CORE  )
synonym <       <             (   .6.1.0480     less-than        CORE  )
synonym <#      <#            (   .6.1.0490     less-number-sign         CORE  )
synonym <>      <>            (   .6.2.0500     not-equals       CORE EXT  )
synonym =       =             (   .6.1.0530     equals   CORE  )
synonym >       >             (   .6.1.0540     greater-than     CORE  )
synonym >BODY   >BODY         (   .6.1.0550     to-body  CORE  )
synonym >FLOAT  >FLOAT        ( 12.6.1.0558     to-float         FLOATING  )
synonym >IN     >IN           (   .6.1.0560     to-in    CORE  )
synonym >NUMBER >NUMBER       (   .6.1.0570     to-number        CORE  )
synonym >R      >R            (   .6.1.0580     to-r     CORE  )
synonym 0<      0<            (   .6.1.0250     zero-less        CORE  )
synonym 0<>     0<>           (   .6.2.0260     zero-not-equals  CORE EXT  )
synonym 0=      0=            (   .6.1.0270     zero-equals      CORE  )
synonym 0>      0>            (   .6.2.0280     zero-greater     CORE EXT  )
synonym 1-      1-            (   .6.1.0300     one-minus        CORE  )
synonym 1+      1+            (   .6.1.0290     one-plus         CORE  )
synonym 2!      2!            (   .6.1.0310     two-store        CORE  )
synonym 2@      2@            (   .6.1.0350     two-fetch        CORE  )
synonym 2*      2*            (   .6.1.0320     two-star         CORE  )
synonym 2/      2/            (   .6.1.0330     two-slash        CORE  )
synonym 2>R     2>R           (   .6.2.0340     two-to-r         CORE EXT )
synonym 2CONSTANT 2CONSTANT   (    8.6.1.0360   two-constant     DOUBLE )
synonym 2DROP   2DROP         (   .6.1.0370     two-drop         CORE  )
synonym 2DUP    2DUP          (   .6.1.0380     two-dupe         CORE  )
synonym 2LITERAL 2LITERAL     (  8.6.1.0390    two-literal      DOUBLE )
synonym 2OVER   2OVER         (   .6.1.0400     two-over         CORE  )
synonym 2R@     2R@           (   .6.2.0415     two-r-fetch      CORE EXT  )
synonym 2R>     2R>           (   .6.2.0410     two-r-from       CORE EXT  )
synonym 2ROT    2ROT          (  8.6.2.0420     two-rote         DOUBLE EXT  )
synonym 2SWAP   2SWAP         (   .6.1.0430     two-swap         CORE  )
synonym 2VARIABLE 2VARIABLE   (   8.6.1.0440    two-variable     DOUBLE )
synonym ABORT   ABORT         (   .6.1.0670              CORE  )
\ synonym ABORT ABORT         (  9.6.2.0670              EXCEPTION EXT  )
synonym ABORT"  ABORT"        (   .6.1.0680     abort-quote      CORE  )
\ synonym ABORT" ABORT"       (  9.6.2.0680     abort-quote      EXCEPTION EXT  )
synonym ABS     ABS           (   .6.1.0690     abs      CORE  )
synonym ACCEPT  ACCEPT        (   .6.1.0695              CORE  )
synonym AGAIN   AGAIN         (   .6.2.0700              CORE EXT  )
synonym AHEAD   AHEAD         ( 15.6.2.0702              TOOLS EXT )
synonym ALIGN   ALIGN         (   .6.1.0705              CORE  )
synonym ALIGNED ALIGNED       (   .6.1.0706              CORE  )
synonym ALLOCATE ALLOCATE     (   14.6.1.0707            MEMORY )
synonym ALLOT   ALLOT         (   .6.1.0710              CORE  )
synonym ALSO    ALSO          ( 16.6.2.0715              SEARCH EXT  )
synonym AND     AND           (   .6.1.0720              CORE  )
synonym ASSEMBLER ASSEMBLER   ( 15.6.2.0740            TOOLS EXT )
synonym AT-XY   AT-XY         ( 10.6.1.0742     at-x-y   FACILITY  )
synonym BASE    BASE          (   .6.1.0750              CORE  )
synonym BEGIN   BEGIN         (   .6.1.0760              CORE  )
synonym BIN     BIN           ( 11.6.1.0765              FILE  )
synonym BL      BL            (   .6.1.0770     b-l      CORE  )
synonym BLANK   BLANK         ( 17.6.1.0780              STRING )
\ synonym BLK   BLK           (  7.6.1.0790    b-l-k     BLOCK  )
\ synonym BLOCK BLOCK         (  7.6.1.0800              BLOCK  )
\ synonym BUFFER BUFFER       (  7.6.1.0820              BLOCK  )
synonym BYE     BYE           ( 15.6.2.0830              TOOLS EXT )
synonym C,      C,            (   .6.1.0860     c-comma  CORE  )
synonym C!      C!            (   .6.1.0850     c-store  CORE  )
synonym C"      C"            (   .6.2.0855     c-quote  CORE EXT  )
synonym C@      C@            (   .6.1.0870     c-fetch  CORE  )
synonym CASE    CASE          (   .6.2.0873              CORE EXT  )
synonym CATCH   CATCH         (  9.6.1.0875              EXCEPTION )
synonym CELL+   CELL+         (   .6.1.0880     cell-plus        CORE  )
synonym CELLS   CELLS         (   .6.1.0890              CORE  )
synonym CHAR    CHAR          (   .6.1.0895     char     CORE  )
synonym CHAR+   CHAR+         (   .6.1.0897     char-plus        CORE  )
synonym CHARS   CHARS         (   .6.1.0898     chars    CORE  )
synonym CLOSE-FILE CLOSE-FILE ( 11.6.1.0900            FILE  )
synonym CMOVE   CMOVE         ( 17.6.1.0910     c-move   STRING )
synonym CMOVE>  CMOVE>        ( 17.6.1.0920     c-move-up        STRING )
synonym CODE    CODE          ( 15.6.2.0930              TOOLS EXT )
synonym COMPARE COMPARE       ( 17.6.1.0935              STRING )
synonym COMPILE, COMPILE,     (   .6.2.0945     compile-comma    CORE EXT  )
synonym CONSTANT CONSTANT     (   .6.1.0950              CORE  )
synonym CONVERT CONVERT       (   .6.2.0970              CORE EXT  ) DEPRECATED
synonym COUNT   COUNT         (   .6.1.0980              CORE  )
synonym CR      CR            (   .6.1.0990     c-r      CORE  )
synonym CREATE  CREATE        (   .6.1.1000              CORE  )
synonym CREATE-FILE CREATE-FILE ( 11.6.1.1010            FILE  )
synonym CS-PICK CS-PICK       ( 15.6.2.1015     c-s-pick         TOOLS EXT )
synonym CS-ROLL CS-ROLL       ( 15.6.2.1020     c-s-roll         TOOLS EXT )
synonym D-      D-            (  8.6.1.1050     d-minus  DOUBLE )
synonym D.      D.            (  8.6.1.1060     d-dot    DOUBLE )
synonym D.R     D.R           (  8.6.1.1070     d-dot-r  DOUBLE )
synonym D+      D+            (  8.6.1.1040     d-plus   DOUBLE )
synonym D<      D<            (  8.6.1.1110     d-less-than      DOUBLE )
synonym D=      D=            (  8.6.1.1120     d-equals         DOUBLE )
synonym D>F     D>F           ( 12.6.1.1130     d-to-f   FLOATING  )
synonym D>S     D>S           (  8.6.1.1140     d-to-s   DOUBLE )
synonym D0<     D0<           (  8.6.1.1075     d-zero-less      DOUBLE )
synonym D0=     D0=           (  8.6.1.1080     d-zero-equals    DOUBLE )
synonym D2*     D2*           (  8.6.1.1090     d-two-star       DOUBLE )
synonym D2/     D2/           (  8.6.1.1100     d-two-slash      DOUBLE )
synonym DABS    DABS          (  8.6.1.1160     d-abs    DOUBLE )
synonym DECIMAL DECIMAL       (   .6.1.1170              CORE  )
synonym DEFINITIONS DEFINITIONS ( 16.6.1.1180            SEARCH )
synonym DELETE-FILE DELETE-FILE ( 11.6.1.1190            FILE  )
synonym DEPTH   DEPTH         (   .6.1.1200              CORE  )
synonym DF!     DF!           ( 12.6.2.1203     d-f-store        FLOATING EXT  )
synonym DF@     DF@           ( 12.6.2.1204     d-f-fetch        FLOATING EXT  )
synonym DFALIGN DFALIGN       ( 12.6.2.1205     d-f-align        FLOATING EXT  )
synonym DFALIGNED DFALIGNED   ( 12.6.2.1207     d-f-aligned      FLOATING EXT  )
synonym DFLOAT+ DFLOAT+       ( 12.6.2.1208     d-float-plus     FLOATING EXT  )
synonym DFLOATS DFLOATS       ( 12.6.2.1209     d-floats         FLOATING EXT  )
synonym DMAX    DMAX          (  8.6.1.1210     d-max    DOUBLE )
synonym DMIN    DMIN          (  8.6.1.1220     d-min    DOUBLE )
synonym DNEGATE DNEGATE       (  8.6.1.1230     d-negate         DOUBLE )
synonym DO      DO            (   .6.1.1240              CORE  )
synonym DOES>   DOES>         (   .6.1.1250     does     CORE  )
synonym DROP    DROP          (   .6.1.1260              CORE  )
synonym DU<     DU<           (  8.6.2.1270     d-u-less         DOUBLE EXT  )
synonym DUMP    DUMP          ( 15.6.1.1280              TOOLS  )
synonym DUP     DUP           (   .6.1.1290     dupe     CORE  )
synonym EDITOR  EDITOR        ( 15.6.2.1300              TOOLS EXT )
synonym EKEY    EKEY          ( 10.6.2.1305     e-key    FACILITY EXT  )
synonym EKEY?   EKEY?         ( 10.6.2.1307     e-key-question   FACILITY EXT  )
synonym EKEY>CHAR EKEY>CHAR   ( 10.6.2.1306     e-key-to-char    FACILITY EXT  )
synonym ELSE    ELSE          (   .6.1.1310              CORE  )
synonym EMIT    EMIT          (   .6.1.1320              CORE  )
synonym EMIT?   EMIT?         ( 10.6.2.1325     emit-question    FACILITY EXT  )
\ synonym EMPTY-BUFFERS EMPTY-BUFFERS   ( 7.6.2.1330             BLOCK EXT )
synonym ENDCASE ENDCASE       (   .6.2.1342     end-case         CORE EXT  )
synonym ENDOF   ENDOF         (   .6.2.1343     end-of   CORE EXT  )
synonym ENVIRONMENT? ENVIRONMENT? ( .6.1.1345   environment-query        CORE  )
synonym ERASE   ERASE         (   .6.2.1350              CORE EXT  )
synonym EVALUATE EVALUATE     (   .6.1.1360              CORE  )
\ synonym EVALUATE EVALUATE   (  7.6.1.1360             BLOCK  )
synonym EXECUTE EXECUTE       (   .6.1.1370              CORE  )
synonym EXIT    EXIT          (   .6.1.1380              CORE  )
synonym EXPECT  EXPECT        (   .6.2.1390              CORE EXT  ) DEPRECATED
synonym F-      F-            ( 12.6.1.1425     f-minus  FLOATING  )
synonym F!      F!            ( 12.6.1.1400     f-store  FLOATING  )
synonym F.      F.            ( 12.6.2.1427     f-dot    FLOATING EXT  )
synonym F@      F@            ( 12.6.1.1472     f-fetch  FLOATING  )
synonym F*      F*            ( 12.6.1.1410     f-star   FLOATING  )
synonym F**     F**           ( 12.6.2.1415     f-star-star      FLOATING EXT  )
synonym F/      F/            ( 12.6.1.1430     f-slash  FLOATING  )
synonym F+      F+            ( 12.6.1.1420     f-plus   FLOATING  )
synonym F<      F<            ( 12.6.1.1460     f-less-than      FLOATING  )
synonym F>D     F>D           ( 12.6.1.1470     f-to-d   FLOATING  )
synonym F~      F~            ( 12.6.2.1640     f-proximate      FLOATING EXT  )
synonym F0<     F0<           ( 12.6.1.1440     f-zero-less-than         FLOATING  )
synonym F0=     F0=           ( 12.6.1.1450     f-zero-equals    FLOATING  )
synonym FABS    FABS          ( 12.6.2.1474     f-abs    FLOATING EXT  )
synonym FACOS   FACOS         ( 12.6.2.1476     f-a-cos  FLOATING EXT  )
synonym FACOSH  FACOSH        ( 12.6.2.1477     f-a-cosh         FLOATING EXT  )
synonym FALIGN  FALIGN        ( 12.6.1.1479     f-align  FLOATING  )
synonym FALIGNED FALIGNED     ( 12.6.1.1483     f-aligned        FLOATING  )
synonym FALOG   FALOG         ( 12.6.2.1484     f-a-log  FLOATING EXT  )
synonym FALSE   FALSE         (   .6.2.1485              CORE EXT  )
synonym FASIN   FASIN         ( 12.6.2.1486     f-a-sine         FLOATING EXT  )
synonym FASINH  FASINH        ( 12.6.2.1487     f-a-cinch        FLOATING EXT  )
synonym FATAN   FATAN         ( 12.6.2.1488     f-a-tan  FLOATING EXT  )
synonym FATAN2  FATAN2        ( 12.6.2.1489     f-a-tan-two      FLOATING EXT  )
synonym FATANH  FATANH        ( 12.6.2.1491     f-a-tan-h        FLOATING EXT  )
synonym FCONSTANT FCONSTANT   ( 12.6.1.1492     f-constant       FLOATING  )
synonym FCOS    FCOS          ( 12.6.2.1493     f-cos    FLOATING EXT  )
synonym FCOSH   FCOSH         ( 12.6.2.1494     f-cosh   FLOATING EXT  )
synonym FDEPTH  FDEPTH        ( 12.6.1.1497     f-depth  FLOATING  )
synonym FDROP   FDROP         ( 12.6.1.1500     f-drop   FLOATING  )
synonym FDUP    FDUP          ( 12.6.1.1510     f-dupe   FLOATING  )
synonym FE.     FE.           ( 12.6.2.1513     f-e-dot  FLOATING EXT  )
synonym FEXP    FEXP          ( 12.6.2.1515     f-e-x-p  FLOATING EXT  )
synonym FEXPM1  FEXPM1        ( 12.6.2.1516     f-e-x-p-m-one    FLOATING EXT  )
synonym FILE-POSITION FILE-POSITION ( 11.6.1.1520        FILE  )
synonym FILE-SIZE FILE-SIZE   ( 11.6.1.1522              FILE  )
synonym FILE-STATUS FILE-STATUS ( 11.6.2.1524            FILE EXT  )
synonym FILL    FILL          (   .6.1.1540              CORE  )
synonym FIND    FIND          (   .6.1.1550              CORE  )
\ synonym FIND  FIND          ( 16.6.1.1550              SEARCH )
synonym FLITERAL FLITERAL     ( 12.6.1.1552     f-literal        FLOATING  )
synonym FLN     FLN           ( 12.6.2.1553     f-l-n    FLOATING EXT  )
synonym FLNP1   FLNP1         ( 12.6.2.1554     f-l-n-p-one      FLOATING EXT  )
synonym FLOAT+  FLOAT+        ( 12.6.1.1555     float-plus       FLOATING  )
synonym FLOATS  FLOATS        ( 12.6.1.1556              FLOATING  )
synonym FLOG    FLOG          ( 12.6.2.1557     f-log    FLOATING EXT  )
synonym FLOOR   FLOOR         ( 12.6.1.1558              FLOATING  )
\ synonym FLUSH FLUSH         (  7.6.1.1559              BLOCK  )
synonym FLUSH-FILE FLUSH-FILE ( 11.6.2.1560              FILE EXT  )
synonym FM/MOD  FM/MOD        (   .6.1.1561     f-m-slash-mod    CORE  )
synonym FMAX    FMAX          ( 12.6.1.1562     f-max    FLOATING  )
synonym FMIN    FMIN          ( 12.6.1.1565     f-min    FLOATING  )
synonym FNEGATE FNEGATE       ( 12.6.1.1567     f-negate         FLOATING  )
synonym FORGET  FORGET        ( 15.6.2.1580              TOOLS EXT ) DEPRECATED
synonym FORTH   FORTH         ( 16.6.2.1590              SEARCH EXT  )
synonym FORTH-WORDLIST FORTH-WORDLIST ( 16.6.1.1595      SEARCH )
synonym FOVER   FOVER         ( 12.6.1.1600     f-over   FLOATING  )
synonym FREE    FREE          ( 14.6.1.1605              MEMORY )
synonym FROT    FROT          ( 12.6.1.1610     f-rote   FLOATING  )
synonym FROUND  FROUND        ( 12.6.1.1612     f-round  FLOATING  )
synonym FS.     FS.           ( 12.6.2.1613     f-s-dot  FLOATING EXT  )
synonym FSIN    FSIN          ( 12.6.2.1614     f-sine   FLOATING EXT  )
synonym FSINCOS FSINCOS       ( 12.6.2.1616     f-sine-cos       FLOATING EXT  )
synonym FSINH   FSINH         ( 12.6.2.1617     f-cinch  FLOATING EXT  )
synonym FSQRT   FSQRT         ( 12.6.2.1618     f-square-root    FLOATING EXT  )
synonym FSWAP   FSWAP         ( 12.6.1.1620     f-swap   FLOATING  )
synonym FTAN    FTAN          ( 12.6.2.1625     f-tan    FLOATING EXT  )
synonym FTANH   FTANH         ( 12.6.2.1626     f-tan-h  FLOATING EXT  )
synonym FVARIABLE FVARIABLE   ( 12.6.1.1630     f-variable FLOATING  )
synonym GET-CURRENT GET-CURRENT ( 16.6.1.1643            SEARCH )
synonym GET-ORDER   GET-ORDER   ( 16.6.1.1647            SEARCH )
synonym HERE    HERE          (   .6.1.1650              CORE  )
synonym HEX     HEX           (   .6.2.1660              CORE EXT  )
synonym HOLD    HOLD          (   .6.1.1670              CORE  )
synonym I       I             (   .6.1.1680              CORE  )
synonym IF      IF            (   .6.1.1700              CORE  )
synonym IMMEDIATE IMMEDIATE   (   .6.1.1710              CORE  )
synonym INCLUDE-FILE INCLUDE-FILE ( 11.6.1.1717          FILE  )
synonym INCLUDED INCLUDED     ( 11.6.1.1718              FILE  )
synonym INVERT  INVERT        (   .6.1.1720              CORE  )
synonym J       J             (   .6.1.1730              CORE  )
synonym KEY     KEY           (   .6.1.1750              CORE  )
synonym KEY?    KEY?          ( 10.6.1.1755     key-question     FACILITY  )
synonym LEAVE   LEAVE         (   .6.1.1760              CORE  )
\ synonym LIST  LIST          (  7.6.2.1770              BLOCK EXT )
synonym LITERAL LITERAL       (   .6.1.1780              CORE  )
\ synonym LOAD  LOAD          (  7.6.1.1790              BLOCK  )
synonym LOCALS| LOCALS|       ( 13.6.2.1795     locals-bar       LOCAL EXT )
synonym LOOP    LOOP          (   .6.1.1800              CORE  )
synonym LSHIFT  LSHIFT        (   .6.1.1805     l-shift  CORE  )
synonym M*      M*            (   .6.1.1810     m-star   CORE  )
synonym M*/     M*/           (  8.6.1.1820     m-star-slash     DOUBLE )
synonym M+      M+            (  8.6.1.1830     m-plus   DOUBLE )
synonym MARKER  MARKER        (   .6.2.1850              CORE EXT  )
synonym MAX     MAX           (   .6.1.1870              CORE  )
synonym MIN     MIN           (   .6.1.1880              CORE  )
synonym MOD     MOD           (   .6.1.1890              CORE  )
synonym MOVE    MOVE          (   .6.1.1900              CORE  )
synonym MS      MS            ( 10.6.2.1905              FACILITY EXT  )
synonym NEGATE  NEGATE        (   .6.1.1910              CORE  )
synonym NIP     NIP           (   .6.2.1930              CORE EXT  )
synonym OF      OF            (   .6.2.1950              CORE EXT  )
synonym ONLY    ONLY          ( 16.6.2.1965              SEARCH EXT  )
synonym OPEN-FILE OPEN-FILE (   11.6.1.1970              FILE  )
synonym OR      OR            (   .6.1.1980              CORE  )
synonym ORDER   ORDER         ( 16.6.2.1985              SEARCH EXT  )
synonym OVER    OVER          (   .6.1.1990              CORE  )
synonym PAD     PAD           (   .6.2.2000              CORE EXT  )
synonym PAGE    PAGE          ( 10.6.1.2005              FACILITY  )
synonym PARSE   PARSE         (   .6.2.2008              CORE EXT  )
synonym PICK    PICK          (   .6.2.2030              CORE EXT  )
synonym POSTPONE POSTPONE     (   .6.1.2033              CORE  )
synonym PRECISION PRECISION   ( 12.6.2.2035            FLOATING EXT  )
synonym PREVIOUS PREVIOUS     ( 16.6.2.2037            SEARCH EXT  )
synonym QUERY   QUERY         (   .6.2.2040              CORE EXT  ) DEPRECATED
synonym QUIT    QUIT          (   .6.1.2050              CORE  )
synonym R@      R@            (   .6.1.2070     r-fetch  CORE  )
synonym R/O     R/O           ( 11.6.1.2054     r-o      FILE  )
synonym R/W     R/W           ( 11.6.1.2056     r-w      FILE  )
synonym R>      R>            (   .6.1.2060     r-from   CORE  )
synonym READ-FILE READ-FILE   ( 11.6.1.2080              FILE  )
synonym READ-LINE READ-LINE   ( 11.6.1.2090              FILE  )
synonym RECURSE RECURSE       (   .6.1.2120              CORE  )
synonym REFILL  REFILL        (   .6.2.2125              CORE EXT  )
\ synonym REFILL REFILL       (  7.6.2.2125              BLOCK EXT )
\ synonym REFILL REFILL       ( 11.6.2.2125              FILE EXT  )
synonym RENAME-FILE RENAME-FILE ( 11.6.2.2130            FILE EXT  )
synonym REPEAT  REPEAT        (   .6.1.2140              CORE  )
synonym REPOSITION-FILE REPOSITION-FILE ( 11.6.1.2142    FILE  )
synonym REPRESENT       REPRESENT       ( 12.6.1.2143    FLOATING  )
synonym RESIZE  RESIZE        ( 14.6.1.2145              MEMORY )
synonym RESIZE-FILE RESIZE-FILE ( 11.6.1.2147            FILE  )
synonym RESTORE-INPUT RESTORE-INPUT ( .6.2.2148          CORE EXT  )
synonym ROLL    ROLL          (   .6.2.2150              CORE EXT  )
synonym ROT     ROT           (   .6.1.2160     rote     CORE  )
synonym RSHIFT  RSHIFT        (   .6.1.2162     r-shift  CORE  )
synonym S"      S"            (   .6.1.2165     s-quote  CORE  )
\ synonym S"    S"            ( 11.6.1.2165     s-quote  FILE  )
synonym S>D     S>D           (   .6.1.2170     s-to-d   CORE  )
\ synonym SAVE-BUFFERS SAVE-BUFFERS ( 7.6.1.2180         BLOCK  )
synonym SAVE-INPUT SAVE-INPUT   ( .6.2.2182              CORE EXT  )
\ synonym SCR   SCR           (  7.6.2.2190     s-c-r    BLOCK EXT )
synonym SEARCH  SEARCH        ( 17.6.1.2191              STRING )
synonym SEARCH-WORDLIST SEARCH-WORDLIST ( 16.6.1.2192 SEARCH   )
synonym SEE     SEE           ( 15.6.1.2194              TOOLS  )
synonym SET-CURRENT SET-CURRENT ( 16.6.1.2195            SEARCH )
synonym SET-ORDER   SET-ORDER   ( 16.6.1.2197            SEARCH )
synonym SET-PRECISION SET-PRECISION ( 12.6.2.2200                FLOATING EXT  )
synonym SF!     SF!           ( 12.6.2.2202     s-f-store        FLOATING EXT  )
synonym SF@     SF@           ( 12.6.2.2203     s-f-fetch        FLOATING EXT  )
synonym SFALIGN SFALIGN       ( 12.6.2.2204     s-f-align        FLOATING EXT  )
synonym SFALIGNED SFALIGNED   ( 12.6.2.2206     s-f-aligned      FLOATING EXT  )
synonym SFLOAT+ SFLOAT+       ( 12.6.2.2207     s-float-plus     FLOATING EXT  )
synonym SFLOATS SFLOATS       ( 12.6.2.2208     s-floats         FLOATING EXT  )
synonym SIGN    SIGN          (   .6.1.2210              CORE  )
synonym SLITERAL SLITERAL     ( 17.6.1.2212              STRING )
synonym SM/REM  SM/REM        (   .6.1.2214     s-m-slash-rem    CORE  )
synonym SOURCE  SOURCE        (   .6.1.2216              CORE  )
synonym SOURCE-ID SOURCE-ID   (   .6.2.2218     source-i-d       CORE EXT  )
\ synonym SOURCE-ID SOURCE-ID ( 11.6.1.2218     source-i-d       FILE  )
synonym SPACE   SPACE         (   .6.1.2220              CORE  )
synonym SPACES  SPACES        (   .6.1.2230              CORE  )
synonym SPAN    SPAN          (   .6.2.2240              CORE EXT  ) DEPRECATED
synonym STATE   STATE         (   .6.1.2250              CORE  )
\ synonym STATE STATE         ( 15.6.2.2250              TOOLS EXT )
synonym SWAP    SWAP          (   .6.1.2260              CORE  )
synonym THEN    THEN          (   .6.1.2270              CORE  )
synonym THROW   THROW         (  9.6.1.2275              EXCEPTION )
\ synonym THRU  THRU          (  7.6.2.2280              BLOCK EXT )
synonym TIB     TIB           (   .6.2.2290     t-i-b    CORE EXT  ) DEPRECATED
synonym TIME&DATE TIME&DATE   ( 10.6.2.2292     time-and-date    FACILITY EXT  )
synonym TO      TO            (   .6.2.2295              CORE EXT  )
\ synonym TO    TO            ( 13.6.1.2295              LOCAL  )
synonym TRUE    TRUE          (   .6.2.2298              CORE EXT  )
synonym TUCK    TUCK          (   .6.2.2300              CORE EXT  )
synonym TYPE    TYPE          (   .6.1.2310              CORE  )
synonym U.      U.            (   .6.1.2320     u-dot    CORE  )
synonym U.R     U.R           (   .6.2.2330     u-dot-r  CORE EXT  )
synonym U<      U<            (   .6.1.2340     u-less-than      CORE  )
synonym U>      U>            (   .6.2.2350     u-greater-than   CORE EXT )
synonym UM*     UM*           (   .6.1.2360     u-m-star         CORE  )
synonym UM/MOD  UM/MOD        (   .6.1.2370     u-m-slash-mod    CORE  )
synonym UNLOOP  UNLOOP        (   .6.1.2380              CORE  )
synonym UNTIL   UNTIL         (   .6.1.2390              CORE  )
synonym UNUSED  UNUSED        (   .6.2.2395              CORE EXT  )
\ synonym UPDATE UPDATE       (  7.6.1.2400             BLOCK  )
synonym VALUE   VALUE         (   .6.2.2405              CORE EXT  )
synonym VARIABLE VARIABLE     (   .6.1.2410              CORE  )
synonym W/O     W/O           ( 11.6.1.2425     w-o      FILE  )
synonym WHILE   WHILE         (   .6.1.2430              CORE  )
synonym WITHIN  WITHIN        (   .6.2.2440              CORE EXT  )
synonym WORD    WORD          (   .6.1.2450              CORE  )
synonym WORDLIST WORDLIST     ( 16.6.1.2460              SEARCH )
synonym WORDS   WORDS         ( 15.6.1.2465              TOOLS  )
synonym WRITE-FILE WRITE-FILE ( 11.6.1.2480              FILE  )
synonym WRITE-LINE WRITE-LINE ( 11.6.1.2485              FILE  )
synonym XOR     XOR           (   .6.1.2490     x-or     CORE  )

also Forth definitions
synonym dpansOnly dpansOnly
DPR-WARNING-ON

dpansOnly \ To switch to dpans

cr cr .( --- DpAnsfCheck active for DPANS'94 --- )
order


\ only forth also definitions \ To switch to normal Forth
\ \s
